
columns_to_ignore = ["chas", "dis", "rad", "ptratio", "black"]

overall_results = [
    {
        "Model": "Linear",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Polynomial",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Z-Score",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Random Forest",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Linear Regression (Less Features)",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Polynomial (Less Features)",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Z-Score (Less Features)",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
    {
        "Model": "Random Forest (Less Features)",
        "MSE Before": 0,
        "MSE After": 0,
        "RMSE Before": 0,
        "RMSE After": 0,
        "MAE Before": 0,
        "MAE After": 0,
    },
]
